### ISSUE TITLE
typed-json array not being updated from DB query

### ISSUE THREAD

**Issue by bouguila** [StarcounterApps/VehicleTrackDemo#1]
### Description 
the property `Vehicles` of type Json Array is filled from database query result.
if the query is limited to fetch only 1 record the bind works otherwise the data remains empty 
### Steps to reproduce
1. clone the repo to your local machine 
2. build and run it using Visual Studio
3. go to http://localhost:8080/
4. open SC debug aid

### Expected result 
Vehicles array should be populated with data fetched from DB
### Actual result 
the array is empty

**Comment by bouguila** [comment]
cc @miyconst

**Comment by miyconst** [comment]
@chrhol please investigate this issue and if it turns out to be Typed JSON problem, then create an issue in `Level1`.

**Comment by chrhol** [comment]
It looks like this is mainly a problem with performance. Some operations take a huge amount of time leading to congestion on the server. 

I found a couple of things for performance and one thing with getting the result from the provider.

1. The query for getting the latest position for a vehicle is extremely slow, it takes ages to execute. It has no index and the `ORDER BY` totally ruins the execution time. 

```
public GpsPosition Position =>
        Db.SQL<GpsPosition>("SELECT p FROM CarTracking.GpsPosition p WHERE p.Vehicle = ? ORDER BY p.Timestmp DESC", this).First;
```

By adding an index for `Vehicle` and `Timestmp` the main problem will be solved.

```
DbIndexHelper.CreateIndex("GPS_Vehicle", "CREATE INDEX GPS_Vehicle ON \"GpsPosition\" (Vehicle, Timestmp DESC)");
```

2. With number one in place, there is still a problem with huge patches sent for every push. Basically the data in the viewmodel is replaced each time, leading to that all vehicles with all positions is sent every time.

I tested with adding a property to `MapPage.json.cs` with the same name as the one in the json-file (i.e. `Vehicles` that returns the query. With this way it will be automatically updated for dirtycheck/push and the patches are much smaller. The callback for the push will also be smaller since it only have to call `CalculatePatchAndPushOnWebSocket`. 

I pushed these changes to `simplifications` branch.

3. The last thing looks like the provider gets angry when querying too often, after a little while there is an exception (which makes the thread silently fail) so I increased the wait between each loop.

**Comment by miyconst** [comment]
@chrhol thank you for the investigation of the app, but my main concern is why JSON binding ignores such things and just returns an empty array?

Such app behavior should be punished hard with appropriate exception.

**Comment by chrhol** [comment]
It doesn't. At least not from what I seen when I tested. the query I mentioned takes up all the time so nothing is ever returned to the client.

**Comment by miyconst** [comment]
The vehicles binding is initialized from client side, checking `starcounter-debug-aid` I saw there some patches from server side, after the client request, those were just empty ping patches, still server did respond.

How it may happen if the incoming patch from the client side was never finished?

**Comment by chrhol** [comment]
What do you mean that the binding is initialized from client? There is a server-side loop in a separate thread that pushes alot of stuff every 300 ms. And everything is updated manually, there are no server-side bindings.

When the index was created it seemed to work fine. I can't see that there is anything to change in TypedJSON for this...

**Comment by miyconst** [comment]
@chrhol during my test I disabled the timer, and limited the binding query to 10 items only. The queries I tested in Administrator panel, they took some time, but executed fine.

Still, nothing were visible in the view-model.

I will check it more precise tomorrow.

**Comment by chrhol** [comment]
Right. So after sleeping on it, I thought about one more thing that concerns binding. 

Default value for `0.0` in json-by-example is `decimal`, not `double` and the values in `GpsLocation` is `double`.  Not sure what this will lead to, will check it once I get to the office.

**Comment by chrhol** [comment]
No, is not a problem. When using all vehicles, patches are reguarly pushed with GPS updates. 

My guess would be that not all vehicles gets updated every time, and when there is a limit on the number of vehicles sent to the client, it simply means that these vehicles are not moving or are not included in the result from the provider. 

Getting all vehicles kind of work, but the patches are massive, and take a lot of time. The duration in the debug-aid, is that only server + transfer time or does it include applying the patches on the client as well?

**Comment by andwah** [comment]
A side note from https://github.com/Starcounter/level1/issues/4130

> As recently detected, in some occurrences, when passive clients are used and the server do a lot of pushes this can lead to increasing memory consumption until the server runs out of memory.

**Comment by chrhol** [comment]
> A side note from Starcounter/level1#4130

Yes, this might be a problem until its solved if the map is left open with no interaction for a long time. As soon as the viewport is changed though, versions will be cleaned up.

Just for fun I changed the datamodel a bit (use `vehicle.Position` as a reference to the last added `GpsPosition`) and used the commented out query that uses the last known location to filter vehicles, and this seem to work. I get regular updates for the vehicles I am currently watching, and it's automatically updated through the binding. And the performance of it seems to be quite ok, even though the query itself is not optimized with proper indexes.

**Comment by chrhol** [comment]
>  The duration in the debug-aid, is that only server + transfer time or does it include applying the patches on the client as well?

A note on this: it looks like the duration is not correct when server pushes, it seems to be calculated from the last time client sent something.

**Comment by bouguila** [comment]
thank you @chrhol for the investigation!
i tested your implementation and it seems not only to work fine, but also looks ways more optimized than the the solution that i implemented in the `develop`  branch.

**Comment by miyconst** [comment]
@bouguila I did a re-check, and server is actually working properly. It turns out that your page is sending 4 (**four**) patches from client upon page load. Server responds first three, and stacks on the last one.

Once the huge query is executed, it actually sends respond for the last patch as well.

Closing this issue, and big thanks to @chrhol for the investigation.
